# Generated by Django 4.0.5 on 2022-06-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='titile',
            new_name='title',
        ),
    ]
